### ISSUE TITLE
New icons for the debugger sideabar and control buttons

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#10]

**Comment by xusheng6** [comment]
Maybe we no longer need a debugger sidebar -- instead we will have one for breakpoints and one for modules, etc

**Comment by tur11ng** [comment]
![image](https://user-images.githubusercontent.com/61602820/173189876-7631c10d-d5a9-4638-85c4-742674c6b6d2.png)
Please consider also improving these icons

**Comment by xusheng6** [comment]
This is already done by stable 3.2.
