### ISSUE TITLE
Target output is lost when target terminates

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/debugger#154]
The Target Terminal window has its contents cleared when the target terminates. Not sure what causes this, but my guess would be the UI switching after the target terminates. 

It is rather inconvenient to lose all the interaction with the target when it terminates. Ideally this should be saved for the last debugging session, if not for multiple sessions (future feature idea?). 

Repro steps:
1. Run any binary that produces output. I used this one: (requires boost via brew) [ztnc.zip](https://github.com/Vector35/debugger/files/8597943/ztnc.zip)
2. Step through the target until some output is generated
3. Observe text in the Target Terminal window
4. Resume the target until it has finished execution
5. Observe the Target Terminal window is cleared

**Comment by xusheng6** [comment]
This is fixed as an unintended side effect of loosing equal comparison on DebuggerController object. Previously, the check is too strict, that after debugging, a different DebuggerController object is constructed so the output is cleared. It is fixed now.

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/debugger/issues/189
