### ISSUE TITLE
Command line arguments are not parsed correctly

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/debugger#156]
Using the binary from https://github.com/Vector35/debugger/issues/154, I attempted to provide the following command line arguments: `-p 12345`. The process printed the following message to stderr: `the argument (' 12345') for option '--port' is invalid`. This signals to me that the debugger parsed the command line arguments as `'-p' ' 12345'` and neglected to skip the space separating the two. The debugger should not include the spaces used to separate command line arguments in those arguments' values.

**Comment by xusheng6** [comment]
We are now having the adapters to handle the command lines
