### ISSUE TITLE
Do not hide registers with a value 0x0

### ISSUE THREAD

**Issue by Xoffio** [Vector35/debugger#173]
When debugger hits a break point an you go to check the bit flags you will see that flags set to zero will not show up.

The next two images shows the bit flags shown are different in two different moments of debugging.
![Screenshot 2022-05-03 115649](https://user-images.githubusercontent.com/38369407/166669986-1df75f4b-767a-4867-8b45-beed757d4f4b.jpg)
![Screenshot 2022-05-03 095921](https://user-images.githubusercontent.com/38369407/166669993-89014d19-1488-40dd-bccc-1a33dea4c8d5.jpg)

I think we need to have the bit flags showing all the time. This is because sometimes we need to modify/change the value of it on the fly.

**Comment by xusheng6** [comment]
oh yes, if we are hiding registers with value 0x0, there is no way to modify it

**Comment by xusheng6** [comment]
This is already done before stable 3.1.
