### ISSUE TITLE
Debugger status should show to the right of Enterprise status

### ISSUE THREAD

**Issue by fuzyll** [Vector35/debugger#174]
The position of these should be reversed:

<img width="202" alt="image" src="https://user-images.githubusercontent.com/607452/166715872-c8f68827-abea-4d8d-bd5a-a5ffd350f9c1.png">

**Comment by psifertex** [comment]
The fact that "no active view" is already gone on latest dev mitigates this somewhat.

**Comment by fuzyll** [comment]
@psifertex I am on latest dev (3.0.3405-dev) and "no active view" is _not_ gone already.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/607452/167202090-105f6312-312e-4adc-9dd5-e552a1ff3cf7.png">

(This seems to be supported by the fact that #167 is still open.)

**Comment by xusheng6** [comment]
I removed the "no active view" string and it now shows nothing when there is no active binaryview. Also I truncate the string if it is longer than 50 chars. The tooltip of the widget shows the full length string.
