### ISSUE TITLE
Some errors print to the status widget instead of the log

### ISSUE THREAD

**Issue by fuzyll** [Vector35/debugger#178]
Related to #141, it looks like some error messages are tossed into the debugger status widget. This is problematic since some of these errors are so long, most users will be unable to stretch the window far enough to see the whole error message. Ideally, these would be logged to the log window in the global area instead.

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/607452/167203086-f2b30ec5-97fb-4221-a575-ccd8d3106d5f.png">

**Comment by xusheng6** [comment]
I intentionally printed that to the status, so when launch failed the user would know about it. Because they may now see the log errors. But that long message is totally unexpected and hilarious.

Maybe errors deserve a message box

**Comment by xusheng6** [comment]
This message too long issue is fixed by supporting a short message when an error occurs. A launch failure is a super important message so we need to display that error in the status bar.
