### ISSUE TITLE
Backtrace and debugger console change font when repositioned

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/debugger#179]
### Before

![image](https://user-images.githubusercontent.com/41548458/167872806-da6af502-b484-4d5c-8872-61b8ce782649.png)
![image](https://user-images.githubusercontent.com/41548458/167872833-687488c4-3af0-473a-9ad7-01505befab84.png)

### After

![image](https://user-images.githubusercontent.com/41548458/167872868-56e45159-ba97-4b76-8e45-b37601453ef0.png)

Notice change to sans-serif font from monospace font.

**Comment by xusheng6** [comment]
Wow I have definitely noticed the difference, but I did not realize that the font has unexpectedly changed. Thanks for the report!

**Comment by xusheng6** [comment]
This has been fixed, and probably was fixed by 8cfe1897c063fa6a590eb1d95d6d867a952c1368
