### ISSUE TITLE
Highlight last changed/edited register(s) during execution.

### ISSUE THREAD

**Issue by tur11ng** [Vector35/debugger#190]

**Comment by xusheng6** [comment]
I think we already have this feature, does it malfunction? If you resume the target and it breaks again, the changed registers will be displayed in a different color

**Comment by tur11ng** [comment]
I don't think it works correctly. I will try again and post a video if it doesn't. If I remember well it didn't work with xmm registers.

**Comment by tur11ng** [comment]
I dont think prints xmm registers works at all basically. Maybe this is related to https://github.com/Vector35/debugger/issues/184 ?
![image](https://user-images.githubusercontent.com/61602820/176288224-d59c3e2e-79b5-4b77-84e9-3f29121b4379.png)

**Comment by xusheng6** [comment]
Oh yes, xmm registers cannot be viewed properly right now. 

How about other (shorter) registers? I believe if they are no longer than 64 bits, it should work fine. If that is the case, we should close this issue.

**Comment by tur11ng** [comment]
The rest work fine. You can close the issue.
