### ISSUE TITLE
Double breakpoint on function header in HLIL.

### ISSUE THREAD

**Issue by tur11ng** [Vector35/debugger#191]
When you put break point on function header on HLIL view and also put breakpoint on the first line after the header this happens

![image](https://user-images.githubusercontent.com/61602820/173189804-35315f08-13f8-4c5b-9a45-1e37ccdb286f.png)
.

**Comment by xusheng6** [comment]
This is a weird UI bug that I have not been able to solve. Will try harder later!

**Comment by xusheng6** [comment]
I believe this is already fixed, though I do not have a specific commit for it.
