### ISSUE TITLE
Sometimes Launching takes forever

### ISSUE THREAD

**Issue by tur11ng** [Vector35/debugger#198]
Maybe this is a personal problem because of my setup (because I'm not using a supported Linux distro), but I mention it here so probably other people can share their thoughts on this. I also want to mention that I don't find any errors logged during the operation. I would love to help with extra logs to help resolve this, if this isn't only me having the issue.

**Comment by psifertex** [comment]
~~Could this be a result of being on the dev branch and having auto update enabled? When you restart and an update is pending it will be silently installed before you restart.~~

~~You can try disabling auto-updates to see if that fixes it for you so you can choose the specific times you want to update.~~

EDIT: Sorry, I missed that we were inside of the debugger repo and thought this was a question about BN itself. Ignore me. :-)

**Comment by xusheng6** [comment]
@st1064870 could you check is there any error message in the debugger status bar, which is located at the lower-left of the main window? Currently, our UI is not doing its best to present any errors. So it might not be very straightforward to see what actually happened

**Comment by xusheng6** [comment]
We ship an LLDB executable with the Binary Ninja. It is located in `$BN_Folder/plugins/lldb`. Can you try to launch your target with the lldb directly to see if it works? If it works, then there might be a bug in my code. Otherwise, the launch itself actually fails, but the UI is not communicating the result with the user. Common reasons for launch failure could be missing executable bit, or insufficient privilege, etc.

**Comment by xusheng6** [comment]
> Could this be a result of being on the dev branch and having auto update enabled? When you restart and an update is pending it will be silently installed before you restart.
> 
> You can try disabling auto-updates to see if that fixes it for you so you can choose the specific times you want to update.

He it talking about launching a program under the debugger, not the BN itself

**Comment by tur11ng** [comment]
Okay, I will try to launch it when at home and I will provide feedback here

**Comment by tur11ng** [comment]
I couldn't find a way to reproduce the bug. It was when I tried to debug a CTF binary. You can close this issue for now.
