### ISSUE TITLE
Use better colors for table column highlighting

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/debugger#199]
The `*StandardHighlightColor` colors are not good for foreground text, especially on light themes. More "semantic" colors such as `RegisterColor` or `AddressColor` should be used instead.

https://github.com/Vector35/debugger/blob/9286ffcf93a6ac72b699aa33b4123d2ac6e7d180/ui/registerswidget.cpp#L127-L149

**Comment by xusheng6** [comment]
This is done in 3a6ca7b3aae8f055ab2ca88674de6d54b5f40fc7
