### ISSUE TITLE
Debugger cannot be killed when some library is missing from the debggable binary.

### ISSUE THREAD

**Issue by tur11ng** [Vector35/debugger#201]
I was trying to solve a CTF where a dynamically linked library was missing from a binary. Debugger could not be killed, it could only be restarted. On exit killing worked fine. I can provide you with the specific binary if you can't reproduce the bug. I'm using an unsupported distro however I don't think it plays a role in this issue because everything else works fine in my setup.

**Comment by xusheng6** [comment]
@st1064870 Could you please test if this still reproduce on the latest dev? If so, could you please attach the binary so that I can test it?

**Comment by tur11ng** [comment]
Still there, the binary is called Coffee Invocation from Hack The Box. You can find the binary in the Reverse Engineering Challenges section. I'm not sure I'm allowed to post the binary here, but you can check it. I generally think that trying reversing some challenges from there will help you spot interesting bugs in BN because most of the programs rely on corner case uses of the underlying platform.

**Comment by xusheng6** [comment]
The file is hosted at https://app.hackthebox.com/challenges/308
