### ISSUE TITLE
Changing executable path makes Binja crash

### ISSUE THREAD

**Issue by cvscade** [Vector35/debugger#203]
Reproduction steps:

1. Create a new, empty file
2. Change executable path for the debugger using settings to the executable you want to debug
3. Run

Platform(s):

macOS Ventura 13.0 Beta 2 M1
macOS Monterey 12.4 M1

I'm trying to do this to get rid of artifacts produced by simply opening the executable that I am unable to replace (trying to not see the VMProtect encrypted strings that are pretty much useless) since it'll save me a lot of memory.

**Comment by xusheng6** [comment]
Currently, the debugger does not work properly if the binary view you are viewing is not the target being debugged. This is an issue that we should address in the future. This crash has nothing to do with changing the executable path.

**Comment by xusheng6** [comment]
Tracked by https://github.com/Vector35/debugger/issues/206
