### ISSUE TITLE
Binary Ninja not moving focus to RIP in linear view when reopening from .bndb file

### ISSUE THREAD

**Issue by richardcurteis** [Vector35/debugger#217]
Binary: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`
OS: `Linux desktop 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
Binja Version: `Version 3.1.3469 Personal (Build ID 93650e26)`

When I open the above binary from `/usr/bin/bash` and start debugging. If I set a breakpoint say, somewhere in main(), when I start the debugging session, the GUI switches to the breakpoint as expected.

I then save the session in `bash.bdnb` and close Binja. If I then reopen binja and click on on `bash.bndb` from within the '_Recent_' section. If I repeat the same steps:

1. Set breakpoint in main()
2. Start debugger

I expect the GUI to focus on the breakpoint.
What actually happens instead is the focus remains at the head of the file (see screenshot) despite the debugger moving through the binaries execution, again, see the stack frame in my screenshot. In order to follow the execution in real time I have to use the 'g' shortcut and copy in the address for `RIP`.

![binja_screenshot](https://user-images.githubusercontent.com/6715506/182626099-0477fc89-6b48-4d00-8b51-37472bb636e9.png)

**Comment by xusheng6** [comment]
This is a rather dummy bug, that we have some issues when navigating in the linear view.
