### ISSUE TITLE
Feature request: Publish LLDB development builds

### ISSUE THREAD

**Issue by bb010g** [Vector35/debugger#238]
**What is the feature you'd like to have?**
When building the debugger, a LLDB development install at `$LLDB_PATH` is required. This is almost provided by `${bn_core_path}/plugins/lldb`, but at least the headers are missing. A published LLDB development build that could be used for `$LLDB_PATH` would make building the debugger outside of Vector 35 much simpler.

**Is your feature request related to a problem?**
I wanted to build the debugger in the process of writing & submitting patch that fixes <https://github.com/Vector35/debugger/issues/237>.

**Are any alternative solutions acceptable?**
If this isn't provided, guidance on what to set `$LLDB_PATH` or `$LLVM_PATH` to in `./open-source.md` would be appreciated.

**Comment by xusheng6** [comment]
Available at https://github.com/Vector35/llvm-artifacts/releases
