### ISSUE TITLE
Feature Request: mouse over current_token features and memory map issue

### ISSUE THREAD

**Issue by robert-yates** [Vector35/debugger#239]
# Mouse over ideas
In disassembly double clicking a register/stack variable should jump to its current value
In disassembly hover over register/stack variable should show its value

# Memory map issue
In the register view double clicking a value should update the memory map before
navigating to it - see image below:

![memSync](https://user-images.githubusercontent.com/1876966/186054354-265bbdab-f902-42c9-8e33-e3826c03e162.jpg)

**Comment by robert-yates** [comment]
memory map issue part of this report is fixed by: #334

**Comment by xusheng6** [comment]
Closing this in favor of https://github.com/Vector35/debugger/issues/106
