### ISSUE TITLE
re-arrange icons and handle overflow

### ISSUE THREAD

**Issue by psifertex** [Vector35/debugger#251]
In the default layout on MacOS the Pause and Resume icons aren't visible which leads to confusion.

We should probably some UI to indicate there are more icons, but at a minimum if we re-order to put attach/dettach at the end (as they're far less common than pause/resume) then that would help.

**Comment by galenbwill** [comment]
it was pointed out that the icons themselves are aesthetically not great yet

**Comment by 0cyn** [comment]
As of commit [01372dc5](https://github.com/Vector35/debugger/commit/01372dc52220d3c988a8c8d2852a35d5c38cad71) and previous commit [2d897734](https://github.com/Vector35/debugger/commit/2d897734f0a24608804044ea7822c8b0f7003e00), Launch, Resume, and Pause, and separately,  Attach and Detach, have been combined into a single slot on the control widget.

This reduces the possible icon count to 7 and makes it much less likely the sidebar will be thin enough to clip any icons.
