### ISSUE TITLE
No clear indication that launch has failed when debugging regedit.exe

### ISSUE THREAD

**Issue by plafosse** [Vector35/debugger#260]
You click 'play' it does some "stuff" and then to return to the state before you clicked play while not debugging and providing no feedback This information is also in the log:

![image](https://user-images.githubusercontent.com/10556585/196782845-6b0d2124-3c40-44c8-94d5-2eb652a3bba4.png)

**Comment by 0cyn** [comment]
Related: #264

**Comment by xusheng6** [comment]
This is probably because running regedit.exe requires admin privilege. Running BN as admin or use remote debugging on the local host should work.

**Comment by xusheng6** [comment]
I will add it to the "known issues" section in the debugger docs

**Comment by xusheng6** [comment]
I suspect the total failure is a result of https://github.com/Vector35/debugger/issues/253. I tested that when the launch fails, the debugger actually prints an error message to the log, `failed to launch`. I improved the error message in https://github.com/Vector35/debugger/commit/8709d5fc23fe9e14779c294de633de812b13fcdf
