### ISSUE TITLE
Hide Unused registers (on by default) hides used registers

### ISSUE THREAD

**Issue by 0cyn** [Vector35/debugger#265]
![image](https://user-images.githubusercontent.com/55725881/196788143-fbf2b8af-cdae-4692-a9ca-50a6308700ef.png)

**Comment by xusheng6** [comment]
@cxnder can you share the binary?

Nvm, I created one

**Comment by xusheng6** [comment]
This is probably because the eax register is not present in LLIL, where we collect the list of used reigsters
