### ISSUE TITLE
LLDB: Breakpoints that are still visually present are not applied to consecutive launches and all need to be removed and reapplied

### ISSUE THREAD

**Issue by 0cyn** [Vector35/debugger#266]
None of these breakpoints applied during an initial run are functional after the process exits, and need to all be manually reapplied to work.

![image](https://user-images.githubusercontent.com/55725881/196788536-fdb1982a-a6a5-48e5-8544-615115c539b8.png)

**Comment by xusheng6** [comment]
This looks like a regression. It works before. Not sure when it gets broken

**Comment by xusheng6** [comment]
It is broken by f1bfb867225d52fcea90817b696a227dde942733

**Comment by xusheng6** [comment]
It is broken for both lldb and dbgeng, but for slightly different reasons

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/debugger/issues/288
