### ISSUE TITLE
Double click in registers view should not jump to unmapped/unreadable memory

### ISSUE THREAD

**Issue by 0cyn** [Vector35/debugger#268]
There is no use case for this I can imagine.

![image](https://user-images.githubusercontent.com/55725881/196790975-fbb98469-57cf-403d-901e-7f367e6d935e.png)

**Comment by xusheng6** [comment]
I kinda disagree with this -- I often times click on the register and see where it gets me to. If I see it gets to an unmapped region, I know it's not gonna be a pointer. I think it's better than doing nothing or pop up a dialog telling the user it points to invalid memory.

**Comment by xusheng6** [comment]
Closing this as we think the current behavior is fine.
