### ISSUE TITLE
Duplicate current instruction tag on instruction that is exactly one-byte long

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/debugger#272]
Debugging this binary on an M2 running macOS 12.6:

[hlil_test.zip](https://github.com/Vector35/debugger/files/9823921/hlil_test.zip)

Stepping into the `_nested_if` function shows multiple instructions (both 0x00000001000009a0 and 0x00000001000009a1) as the current instruction. Stepping again works as expected and fixes the issue.

<img width="533" alt="Screen Shot 2022-10-19 at 2 05 59 PM" src="https://user-images.githubusercontent.com/7007406/196793195-dd7b18cf-3de0-49d5-9913-4dcbbe132740.png">

This was performed on an ASAN build so it ran a bit slower than normal, which means this could be related to timing.

**Comment by 0cyn** [comment]
![image](https://user-images.githubusercontent.com/55725881/196805620-01dead3b-b5eb-4e63-b897-ec8ddf27cc0a.png)

This repros at the entry point breakpoint as well

**Comment by xusheng6** [comment]
This is a known issue that I have long sought to fix. It might be a BN bug rather than a debugger one -- that I verified the debugger sets and removes the current instruction tag properly, yet the tag still shows twice. This can be verified by viewing the tag list in the sidebar. 

I will circle back to it later.

**Comment by xusheng6** [comment]
![Screen Shot 2022-10-20 at 4 48 27 PM](https://user-images.githubusercontent.com/94503187/196902022-5afacbce-fa34-417e-bf03-d70bade02886.png)

As can be seen from the screenshot, there is really only tag at the correct address, yet the view rendered two

**Comment by xusheng6** [comment]
The speed of ASAN is probably not related, because the redundant current instruction tag is on the next instruction, not the current one

**Comment by xusheng6** [comment]
This is broken by https://github.com/Vector35/binaryninja-api/issues/3568, in particular related to the handling of disassembly text post-processing

**Comment by xusheng6** [comment]
This is fixed since https://github.com/Vector35/binaryninja-api/issues/3568 is fixed
