### ISSUE TITLE
Breakpoints and Registers context menus do not check for validity on any of their options

### ISSUE THREAD

**Issue by 0cyn** [Vector35/debugger#273]
Neither of these are runnable actions as I have not right-clicked a list item. Registers view also has this issue.

![image](https://user-images.githubusercontent.com/55725881/196794756-58247304-7f7c-45b7-8662-64b2894b415b.png)

**Comment by xusheng6** [comment]
Fixed https://github.com/Vector35/debugger/commit/d31cf7b23c7a53f12873dbadb7e88515141cf726
