### ISSUE TITLE
Registers menu should only allow selecting one register at a time

### ISSUE THREAD

**Issue by 0cyn** [Vector35/debugger#278]
Ideally, it would be able to handle copying/zeroing multiple selected registers, but if that isn't the case, it should at least not allow you to select multiple.

![image](https://user-images.githubusercontent.com/55725881/196798538-0b2a117d-b33f-48d9-8460-f0305f2cc9ad.png)

**Comment by xusheng6** [comment]
I do not think it is very useful to zero multiple registers together, so I changed the title

**Comment by jonpalmisc** [comment]
I /do/ think it would be useful to zero multiple registers at once, but am going to implement this as specified in the title for the time being.
