### ISSUE TITLE
Accessing `dbg.live_view` in Python console causes error 

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#285]
```
>>> dbg.live_view
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 2019, in __repr__
    length = len(self)
OverflowError: cannot fit 'int' into an index-sized integer
```

This is related to https://github.com/Vector35/binaryninja-api/issues/2081. Basically, the debugger binary view is covering the entire memory space for the 64bit, i.e., 0xffffffffffffffff, so it triggers the Python issue. However, issue https://github.com/Vector35/binaryninja-api/issues/2081 is marked as fixed, not sure if there is a regression

**Comment by 0cyn** [comment]
We deprecated the operator and then continued to use it. 

This should be resolved as of API commit https://github.com/Vector35/binaryninja-api/commit/683b07bba5adad52811c324725ebce783ad3ec84
