### ISSUE TITLE
Crash when restarting debug session

### ISSUE THREAD

**Issue by matthewfarrellex** [Vector35/debugger#296]
Version: 3.2.3798-dev Personal (Build ID eb95b32e)
Windows 10 (x64)

I found a crash when restarting debug session but I can not reproduce it again. But I've a crash dump of it. After a bit inspection, I found there is a null pointer dereference issue at https://github.com/Vector35/debugger/blob/01372dc52220d3c988a8c8d2852a35d5c38cad71/core/adapters/dbgengadapter.cpp#L291-L300

It calls `m_debugClient->Release`  outside of checking `m_debugClient` is null or not. And there is a time `m_debugClient` is null when `Reset` is called. I guess it should be `SAFE_RELEASE(this->m_debugClient)`.

**Comment by xusheng6** [comment]
Thx for the bug report and troubleshooting! I will fix it ASAP
