### ISSUE TITLE
Show hotkeys when hovering over the debugger controls

### ISSUE THREAD

**Issue by galenbwill** [Vector35/debugger#339]
Tooltips for debugger controls should include hotkeys (which should reflect the current keybindings of course, not just hard-coded to the defaults).

**Comment by xusheng6** [comment]
This is related to #316. Basically, the actions in the debugger menu, debugger context menu, and the controls widget are all different. We should unify the three of them

**Comment by xusheng6** [comment]
Added in 2d387a9dbf4b03d374c8f1d4fb184f7a84dd46b7
