### ISSUE TITLE
Debugger binary view should be able to show bytes in alignment gaps

### ISSUE THREAD

**Issue by galenbwill** [Vector35/debugger#340]
When a structure ending on a non-aligned boundary leaves a gap in memory before the next aligned structure starts, the bytes in that gap should be shown between the structures in the Debugger binary view's rendering of process memory.

**Comment by xusheng6** [comment]
@galenbwill Could you explain it a little bit? I did not quite get this

**Comment by galenbwill** [comment]
Never mind. Looks like this is already fixed.
