### ISSUE TITLE
Support for listing threads

### ISSUE THREAD

**Issue by op2786** [Vector35/debugger#374]
Currently, we can see thread list in stack trace widget but it can be improved in different ways. For example:

* We can have another tab in the debugger sidebar like registers /breakpoints
* We can have another widget in global area
* We can modify the thread frames widget into tree view and make it list threads as first level, and thread frames of the thread if expanded

**Comment by xusheng6** [comment]
Also fixed in 5372a0f1411afd3ca4f22f635a77c72b0afe812f
