### ISSUE TITLE
Disble LLDB for native debugging on Windows

### ISSUE THREAD

**Issue by op2786** [Vector35/debugger#376]
Looks like LLDB can not restore original bytes for breakpoints on windows. If I override IP, seems like continue, step into /over etc works.

![lldb](https://user-images.githubusercontent.com/109607896/202721470-453c46fb-e9ed-4761-8fad-00e999d3c1f4.png)

Probably related to #124

Reading address from LLDB backend:
```
x  0x401710
0x00401710: cc 83 ec 28 c7 05 22 9a 00 00 00 00 00 00 e8 3d  ...(.."........=
0x00401720: 54 00 00 48 83 c4 28 e9 84 fa ff ff 90 90 90 90  T..H..(.........
```

**Comment by xusheng6** [comment]
Tracked upstream by https://github.com/llvm/llvm-project/issues/60063
