### ISSUE TITLE
Failure to connect to remote GDB server

### ISSUE THREAD

**Issue by 0ptyx** [Vector35/debugger#447]
Alright can someone tell me if I'm doing this wrong?
Say  I've launched a program with `gdbserver :9999 my-prog` in a docker container with port localhost port fowarding. How would I connect to it using the Binary Ninja debugger? Is it `Connect to debug server` or `Connect to remote process`? If I use debug server, trying to run the program gives me this error:
```
LLDB Failed to launch target with "error: 'A' packet returned an error: 8"
```
And trying `Connect to remote process` just causes Binaryninja to crash.

**Comment by xusheng6** [comment]
You should use `Connect to remote process`. The crash is a bug. Interestingly, we have noticed that earlier, but the issue is tracked by https://github.com/Vector35/debugger/issues/445
