### ISSUE TITLE
Support loading crash dump

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#458]

**Comment by Xienim** [comment]
Hello,

Currently, you can work with dumps using my plugin. Essentially, you can perform all tasks related to dump analysis, from loading memory allocated by the dumped process into the Binary Ninja database to extracting information or modules from the dump file. The plugin supports both full dumps and mini dumps.

https://github.com/Invodex/Ninja_Dumper

**Comment by xusheng6** [comment]
> Hello,
> 
> Currently, you can work with dumps using my plugin. Essentially, you can perform all tasks related to dump analysis, from loading memory allocated by the dumped process into the Binary Ninja database to extracting information or modules from the dump file. The plugin supports both full dumps and mini dumps.
> 
> https://github.com/Invodex/Ninja_Dumper

This looks cool, I will check it out! 

Just FYI that we have also added the ability to load a Windows dump file this year https://github.com/Vector35/debugger/commit/d45ca39e127b294c1a3b1362fed344784b495c52, though the documentation fails behind a bit

**Comment by xusheng6** [comment]
I am closing this because https://github.com/Vector35/debugger/issues/648 now has more details
