### ISSUE TITLE
Breakpoint does not work if the executable is not PIE on Linux

### ISSUE THREAD

**Issue by ret2void** [Vector35/debugger#499]
你好，xusheng
现在的调试器好像不支持PIE程序的断点。
在一个没有开启PIE的程序中，某指令的地址为0x1234，此时下断点会下到0x1234,这将会正常工作。
但是如果程序开启了pie,指令的地址可能是0x401234,但此时断点仍然位于0x1234,断点将无法工作。
这应该是一个很严重的缺陷。
我的软件版本是3.5.4377,系统是ubuntu 22.04

**Comment by xusheng6** [comment]
> 你好，xusheng
> 
> 现在的调试器好像不支持PIE程序的断点。
> 
> 在一个没有开启PIE的程序中，某指令的地址为0x1234，此时下断点会下到0x1234,这将会正常工作。
> 
> 但是如果程序开启了pie,指令的地址可能是0x401234,但此时断点仍然位于0x1234,断点将无法工作。
> 
> 这应该是一个很严重的缺陷。
> 
> 我的软件版本是3.5.4377,系统是ubuntu 22.04

你好，我们的调试器是支持PIE断点的。但可能有bug导致它不能按照预期工作。请问您是否方便提供一个可以触发这个bug的二进制文件以及复现步骤？谢谢！

**Comment by ret2void** [comment]
我在ubuntu 22.04 lts上创建了如下文件：
int main(){
  return 0;
}
编译选项：gcc 1.c -o 1 -no-pie
下断点：
![图片](https://github.com/Vector35/debugger/assets/83763549/e1fc912d-8593-442c-98ba-34b00fbee04a)
此时运行会发现并没有断下来，在lldb里看一下断点：
![图片](https://github.com/Vector35/debugger/assets/83763549/74b88349-8386-40d5-8854-bf2896b08942)

**Comment by xusheng6** [comment]
> 我在ubuntu 22.04 lts上创建了如下文件：
> 
> int main(){
> 
>   return 0;
> 
> }
> 
> 编译选项：gcc 1.c -o 1 -no-pie
> 
> 下断点：
> 
> ![图片](https://github.com/Vector35/debugger/assets/83763549/e1fc912d-8593-442c-98ba-34b00fbee04a)
> 
> 此时运行会发现并没有断下来，在lldb里看一下断点：
> 
> ![图片](https://github.com/Vector35/debugger/assets/83763549/74b88349-8386-40d5-8854-bf2896b08942)
> 
> 

好的，我尝试复现一下

**Comment by xusheng6** [comment]
Yeah I can reproduce this, thx for the bug report!

**Comment by ret2void** [comment]
顺便问一下调试器是否有办法支持一些堆的分析，例如gdb的pwndbg插件中可以直接查看所有chunk的信息？



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 10, 2023 10:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Vector35/debugger] breakpoint issue (Issue #499)




 
Yeah I can reproduce this, thx for the bug report!

**Comment by xusheng6** [comment]
> 顺便问一下调试器是否有办法支持一些堆的分析，例如gdb的pwndbg插件中可以直接查看所有chunk的信息？
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Jul 10, 2023 10:28 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Vector35/debugger] breakpoint issue (Issue #499) Yeah I can reproduce this, thx for the bug report! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Please see https://github.com/Vector35/debugger/issues/195 and https://github.com/Vector35/debugger/issues/96.

**Comment by xusheng6** [comment]
This is an LLDB bug. Related to 3785496439275488437908020743273952631945

**Comment by CodeXTF2** [comment]
its happening for me too, my breakpoints arent working on the ret2win32 binary

**Comment by xusheng6** [comment]
This is a non-PIE ELF binary that can be used for testing for this issue

[test_no_pie.zip](https://github.com/Vector35/debugger/files/13839305/test_no_pie.zip)
