### ISSUE TITLE
Double clicking an address token does not navigate to it in the debugger binary view when the address is only navigable in a different view

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#557]
I am pretty sure this is a somewhat recent regression, and it is probably NOT caused by the debugger

In the below screenshot, I expect BN to navigate to the address when the `data_100003f90` token is double-clicked

![Screenshot 2024-03-13 at 12 49 22 PM](https://github.com/Vector35/debugger/assets/94503187/549c5544-49f6-4747-9c5b-b78ff8a6ebff)

**Comment by xusheng6** [comment]
This is broken in 4.0.4902-dev

**Comment by xusheng6** [comment]
This is broken by a214f0e2f812182b99163dc06918ec1d33826c12

**Comment by xusheng6** [comment]
Surprisingly, this is actually caused by this tiny change: https://github.com/Vector35/debugger/commit/a214f0e2f812182b99163dc06918ec1d33826c12#diff-f0a8821496b02baa811e75907d143b4d68cf30c4649ddfb81efa3f0ac78296c4. It sets the parent view of the debugger null view to nullptr, and our navigation code relies on the ability to find the raw view all the way back to the binary data. So it breaks

**Comment by xusheng6** [comment]
Re-opened to track for SP1

**Comment by xusheng6** [comment]
Re-opened to track for SP1

**Comment by plafosse** [comment]
Fixed in 4.0.4958-stable
