### ISSUE TITLE
Enhancement -> WINDOWS_KERNEL: Variable Propagation

### ISSUE THREAD

**Issue by FuzzySecurity** [Vector35/debugger#558]
The debugger should propagate variables in the decompiler, I guess this is a work in progress but worth to track in an issue here.

![image](https://github.com/Vector35/debugger/assets/10997340/940d3357-d67d-49ac-96c7-8554359caa2a)

**Comment by xusheng6** [comment]
Hi @FuzzySecurity, thx for the bug report! Could you please explain what you mean by "propagate variables"?

**Comment by xusheng6** [comment]
Closing as duplicate of https://github.com/Vector35/debugger/issues/109
