### ISSUE TITLE
Enhancement -> WINDOWS_KERNEL: Branch Highlighting

### ISSUE THREAD

**Issue by FuzzySecurity** [Vector35/debugger#559]
There should be a mechanism to highlight where the control-flow will go based on state received from the debugger. You know you can highlight the line in the graph or something similar in decompiled representation.

![image](https://github.com/Vector35/debugger/assets/10997340/81fbe9b5-6ab6-468a-9b27-6d3c3eeb53c9)

**Comment by xusheng6** [comment]
Duplicate of: https://github.com/Vector35/debugger/issues/83. This issues has been around for a file since it requires some changes on BN to be able to programmatically highlight the edge

**Comment by xusheng6** [comment]
Closing as duplicate of #83. Also we now have a debugger info widget which shows info of branch take/not taken in a sidebar widget (https://github.com/Vector35/debugger/issues/406)
