### ISSUE TITLE
BUG -> WINDOWS_KERNEL: Decompilation/Symbols

### ISSUE THREAD

**Issue by FuzzySecurity** [Vector35/debugger#561]
I noticed that when debugging it would incorrectly disassemble sometimes when I would hit a breakpoint. I think this generally need some improvement still. Especially if you are debugging a target you have locally on your machine, there shouldn't be a reason for binja to then incorrectly decompile on break or forget what a function is called (rename it to something like `sub_fffff8041fa1125f` or whatever).

I know it's early days, I'm just brain dumping issues from a few hours of debugging a remote target.

**Comment by FuzzySecurity** [comment]
An example here
![image](https://github.com/Vector35/debugger/assets/10997340/5af1af7f-035d-4156-b873-fbfbbfcf1ca2)

It happens a bit randomly and the can start re-analysing etc

![image](https://github.com/Vector35/debugger/assets/10997340/569a1b37-61cc-461f-ade2-00537b732db3)

I haven't tested this properly but I assume this can be an issue as well if you happen to save the bndb because I guess it will overwrite some analysis you may have done at that point. In this case have a bndb copy outside the vm so I don't have many concerns.

**Comment by FuzzySecurity** [comment]
This generally causes quite a few issues, even when single stepping it will jump back and forth between he correct decompilation and random bytes it also crashed my binja client twice. Another issue here is that, when there is a call to an external function (eg ObfReferenceObject in nt) it doesn't show the symbol even though it is correctly resolved in the local dndb.

I think some work is generally needed here, probably across a number of releases.

**Comment by xusheng6** [comment]
Could you please provide a concrete repro step so that I can troubleshoot this?

**Comment by xusheng6** [comment]
This is caused by the way we handle the memory cache previously. This has been fixed in #587
