### ISSUE TITLE
Consider releasing musl binaries

### ISSUE THREAD

**Issue by elde-n** [Vector35/debugger#564]
Manually building is a pain since I have to clone Qt and libclang to my **HOME** directory temporarily so please consider releasing musl binaries thank you.

**Comment by xusheng6** [comment]
Hi @elde-n, I am not entirely sure what you mean. If you are talking about building LLDB/Qt, then you do not need to -- we have published the build artifacts for them, which you can download and use:

1. https://github.com/Vector35/qt-artifacts/releases
2. https://github.com/Vector35/lldb-artifacts/releases

If you are talking about something different, further explanation would be appreciated!

Also, I am curious if you plan to contribute some code to the repo? If so, we would like to get in touch with you first and coordinate the effort. Thanks in advance!

**Comment by elde-n** [comment]
Um nevermind binaryninja doesn't even support musl I just got it to run with gcompat but I was getting errors about ```libdebuggercore.so``` that's why I decided to open this issue. Although it would be nice if binaryninja officially supported musl.
