### ISSUE TITLE
Crash when debugging linux binary on windows with binja free

### ISSUE THREAD

**Issue by negasora** [Vector35/debugger#566]
Only happens on windows

1. Open [go_go_gadget.txt](https://github.com/Vector35/debugger/files/14922897/go_go_gadget.txt) in binja free
2. Try debugging
3. Crash

**Comment by xusheng6** [comment]
@negasora how did you try to debug it? Did you try to debug it directly? (which would not work, but also should not crash), or you setup a remote debugging?

**Comment by negasora** [comment]
Just ran it directly, expected it to error but not crash
