### ISSUE TITLE
Executing GDB commands

### ISSUE THREAD

**Issue by kim366** [Vector35/debugger#59]
The debugger is working nicely for me (at least after patching a file). Unfortunately its functionality is a bit limited and I'd love to be able to send GDB commands directly to the debugger.

Is such functionality available? If not, where would I go about adding it?

**Comment by xusheng6** [comment]
We already support running LLDB/Windbg commands. GDB commands should be supported as soon as we add support for gdb back-end, https://github.com/Vector35/debugger/issues/170
