### ISSUE TITLE
a reached breakpoint causes an analysis hang on dev

### ISSUE THREAD

**Issue by robert-yates** [Vector35/debugger#604]
if you open notepad.exe on windows and start the debugger, then place a breakpoint in main(after entry breakpoint is reached), once the breakpoint is reached binja will start to lag and the status message is stuck at: `Analysis Phase 1...Disassembling (587/587)`

I found the build where this started
4.2.5758.dev commercial - fail - problem starts at this build
4.2.5757.dev commercial - ok

not sure where to find the dev build changelog, or if its ok to post bug reports here for dev builds? :)

/Rob.

**Comment by xusheng6** [comment]
The offending commit corresponding to dev 4.2.5758 is https://github.com/Vector35/binaryninja/commit/5d79111bffe6c0b0464a44e8e294e4398cdd48c2

**Comment by xusheng6** [comment]
Fixed by https://github.com/Vector35/binaryninja/commit/dbb0b8741e1ba12b2ce6bfbc1464999a8a5cc416 and in dev 4.2.5828
