### ISSUE TITLE
Debugger Modules elements overlap

### ISSUE THREAD

**Issue by rose4096** [Vector35/debugger#61]
<img src="https://i.imgur.com/W9GNDEn.gif"/>

Issue -> 
When pulling the UI elements closer together the text ends up overlapping. This could be fixed with a restriction on how far back they can be pulled, rendering less of the string, or fixing the layering.

Steps to reproduce -> 
1) Pull any of the elements closer together. (shown in gif)

**Comment by xusheng6** [comment]
This is already fixed, though I do not have a specific commit for it
