### ISSUE TITLE
Database becomes corrupted after using the debugger

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#612]
A user reported that his database becomes corrupted after using the debugger and then saving the database. He is using the latest free version. The database can still be opened, but all of his annotations, e.g., function names, user types, are gone.

I managed to fix his database by using the experimental "database viewer" (only available in a paid version) and reverting it to an earlier snapshot. Still, we should look into what has happened and avoid this from happening in the future

**Comment by xusheng6** [comment]
The corrupted database is shared in private. V35 folks should find it via "super key time resort hair"

**Comment by xusheng6** [comment]
So it appears that the issue is at least partially related to rebasing. In the below screenshot, we can see in the not-corrupted version of the database, the `SexyBoard::get_gem_at_pixel` function is at `0x6a4121`:

![Screenshot 2024-09-05 at 1 31 24 PM](https://github.com/user-attachments/assets/c7150aaf-cec0-4a8d-9ba3-a2ed759eea74)

However, its address becomes `0xaa4121` in the corrupted database:

![Screenshot 2024-09-05 at 1 33 03 PM](https://github.com/user-attachments/assets/a4453f1e-4343-4713-9e0c-b308e05bb620)

We can see the bytes at 0x6a4121 still appears to be the byte content of the function, I am not sure how it gets to the current state

**Comment by xusheng6** [comment]
Also the memory map of the corrupted and not-corrupted database is exactly the same:

![Screenshot 2024-09-05 at 1 36 28 PM](https://github.com/user-attachments/assets/cb1244c2-efb5-453b-9efa-d8c0d5c17199)

This should NOT be the case IMO, since obviously the rebasing should have moved the segments. Although this does NOT explain various other strange things, e.g., like why user types are missing, it could be the case that once a certain part of the deserialization process fails fatally, the core bails out and decided to not try to further deserliaze

**Comment by xusheng6** [comment]
I also get a ton of errors like this when I open the database:

![Screenshot 2024-09-05 at 1 40 19 PM](https://github.com/user-attachments/assets/7c4e00ec-ca37-4461-af54-71dac8f16ec0)

This confirms my guess that rebasing is related to the issue

**Comment by xusheng6** [comment]
In the offending snapshot, I am seeing this change in the PE/memory_map:

```
{
    "next_order_id": 3,
    "targets": [],
    "regions": [
        {
            "start": 0,
            "end": 4194303,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 4194304,
            "end": 4198399,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "segment": 4194304
                }
            ]
        },
        {
            "start": 4198400,
            "end": 8218267,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "segment": 4198400
                }
            ]
        },
        {
            "start": 8218268,
            "end": 8220671,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 8220672,
            "end": 8704249,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "segment": 8220672
                }
            ]
        },
        {
            "start": 8704250,
            "end": 8708095,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 8708096,
            "end": 8761343,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "segment": 8708096
                }
            ]
        },
        {
            "start": 8761344,
            "end": 19321439,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 19321440,
            "end": 19324927,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 19324928,
            "end": 19741467,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "segment": 19324928
                }
            ]
        },
        {
            "start": 19741468,
            "end": 19741471,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 19741472,
            "end": 19742703,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 19742704,
            "end": 19742723,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        },
        {
            "start": 19742724,
            "end": 4294967294,
            "objects": [
                {
                    "name": "debugger",
                    "order_id": 2,
                    "enabled": true
                },
                {
                    "name": "origin<PE>",
                    "order_id": 0,
                    "enabled": true,
                    "fill": 0
                }
            ]
        }
    ]
}
```

**Comment by mitterdoo** [comment]
I'm the user in question. Just leaving a note in here so I can keep track of the progress and give any additional stuff as needed

**Comment by xusheng6** [comment]
![image](https://github.com/user-attachments/assets/9056700c-29e8-44f8-9c02-607f416fa255)

I browsed the undo action history to see what the user has done that may have caused the corruption. It turns out that after the entry "4 actions", the functions start to show up at wrong locations. And I will see what exactly are the 4 actions

Also, surprisingly, the issue is .exe itself does not support ASLR at all, and when I debug it, it is always loaded at the same address

**Comment by xusheng6** [comment]
![Screenshot 2024-09-05 at 6 43 48 PM](https://github.com/user-attachments/assets/607edc69-5e03-4f2e-8b58-9422f7942f76)

I dumped the actions and there does not seem to be anything outstanding 

@mitterdoo can you recall if this is the time when you started debugging?

**Comment by xusheng6** [comment]
Also @mitterdoo did you manually rebase the binary during debugging?

**Comment by mitterdoo** [comment]
@xusheng6 The highlighted line in the history looks to be around the same time I started debugging. (`do_the_math` was quite the pain to decipher!)
I didn't manually rebase during debugging, but I did get it rebased much earlier in the timeline of the project, to `0x400000` i believe. That was done long before I started debugging.

**Comment by xusheng6** [comment]
> @xusheng6 The highlighted line in the history looks to be around the same time I started debugging. (`do_the_math` was quite the pain to decipher!) I didn't manually rebase during debugging, but I did get it rebased much earlier in the timeline of the project, to `0x400000` i believe. That was done long before I started debugging.

Sure, thx for confirming that I have find the time point where you started debugging. The manual rebasing you did before starting debugging might be playing a role, since we have not tested such interactions beforehand

**Comment by xusheng6** [comment]
> @xusheng6 The highlighted line in the history looks to be around the same time I started debugging. (`do_the_math` was quite the pain to decipher!) I didn't manually rebase during debugging, but I did get it rebased much earlier in the timeline of the project, to `0x400000` i believe. That was done long before I started debugging.

I checked and the .exe you share with me is originally based at 0x400000, can you try to recall how you actually rebased it?

**Comment by xusheng6** [comment]
Hi @mitterdoo , would you like to join our slack so that I can discuss the issue with you directly? https://slack.binary.ninja/

**Comment by xusheng6** [comment]
A more readable version of the memory map when I open the database and run `bv.memory_map`:

```
>>> bv.memory_map
{'MemoryMap': [{'address': 4194304,
                'length': 4096,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 4,
                             'name': 'origin<PE>@0x0',
                             'target': True}]},
               {'address': 4198400,
                'length': 4019868,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 21,
                             'name': 'origin<PE>@0x1000',
                             'target': True}]},
               {'address': 8220672,
                'length': 483578,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 12,
                             'name': 'origin<PE>@0x3d7000',
                             'target': True}]},
               {'address': 8708096,
                'length': 53248,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 14,
                             'name': 'origin<PE>@0x44e000',
                             'target': True}]},
               {'address': 8761344,
                'length': 10560096,
                'objects': [{'absolute_address_mode': False,
                             'enabled': True,
                             'fill': 0,
                             'flags': 14,
                             'name': 'unbound_origin<PE>@0x44e000',
                             'target': False}]},
               {'address': 19324928,
                'length': 416540,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 12,
                             'name': 'origin<PE>@0xe6e000',
                             'target': True}]},
               {'address': 19741472,
                'length': 1232,
                'objects': [{'absolute_address_mode': False,
                             'enabled': True,
                             'fill': 0,
                             'flags': 0,
                             'name': 'unbound_origin<PE>@0xed3b20',
                             'target': False}]},
               {'address': 19742704,
                'length': 20,
                'objects': [{'absolute_address_mode': False,
                             'enabled': True,
                             'fill': 0,
                             'flags': 0,
                             'name': 'unbound_origin<PE>@0xed3ff0',
                             'target': False}]}]}
```

**Comment by xusheng6** [comment]
Compared with what I get if I open the .exe and run the same command:

```
>>> bv.memory_map
{'MemoryMap': [{'address': 4194304,
                'length': 4096,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 4,
                             'name': 'origin<PE>@0x0',
                             'target': True}]},
               {'address': 4198400,
                'length': 4019868,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 21,
                             'name': 'origin<PE>@0x1000',
                             'target': True}]},
               {'address': 8220672,
                'length': 483578,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 12,
                             'name': 'origin<PE>@0x3d7000',
                             'target': True}]},
               {'address': 8708096,
                'length': 53248,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 14,
                             'name': 'origin<PE>@0x44e000',
                             'target': True}]},
               {'address': 8761344,
                'length': 10560096,
                'objects': [{'absolute_address_mode': False,
                             'enabled': True,
                             'fill': 0,
                             'flags': 14,
                             'name': 'unbound_origin<PE>@0x44e000',
                             'target': False}]},
               {'address': 19324928,
                'length': 416540,
                'objects': [{'absolute_address_mode': True,
                             'enabled': True,
                             'flags': 12,
                             'name': 'origin<PE>@0xe6e000',
                             'target': True}]},
               {'address': 19741472,
                'length': 1232,
                'objects': [{'absolute_address_mode': False,
                             'enabled': True,
                             'fill': 0,
                             'flags': 0,
                             'name': 'unbound_origin<PE>@0xed3b20',
                             'target': False}]},
               {'address': 19742704,
                'length': 20,
                'objects': [{'absolute_address_mode': False,
                             'enabled': True,
                             'fill': 0,
                             'flags': 0,
                             'name': 'unbound_origin<PE>@0xed3ff0',
                             'target': False}]}]}
```

**Comment by xusheng6** [comment]
I am kinda confused, the two versions (one in the corrupted database, one from directly opening the .exe) of the memory map are indeed the same. But the database viewer clearly says the `PE/memory_map` has changed

**Comment by xusheng6** [comment]
I noticed an error message `[Default] Error while applying snapshot data: Requesting value 'PE/func_windows-x86_4010c0/data' that does not exist`, I guess the database loading is aborted afterwards, which explains why most of the user annotations are gone

**Comment by xusheng6** [comment]
Oh nvm I figured out. Repro steps:

1. Use the last stable (4.1.5902) and NOT the lastest dev because it has been fixed on the latest dev
2. Load the helloworld.exe
3. Rename the `main` function to `foobar`
4. Start debugging
5. Once the target stops, save the database
6. Kill the target, close the database, and do not save it when asked
7. Re-open the database, see the main function is still called main and not foobar
8. Open the database view, and see in the last snapshot, the `PE/memory_map` has been changed

If I repeat the same process on the latest dev, then things are not broken. I have attached the two database for comparison:

[helloworld2.exe.zip](https://github.com/user-attachments/files/16905917/helloworld2.exe.zip)

**Comment by mitterdoo** [comment]
Sorry for the lack of responses @xusheng6 , just been busy with stuff lately.

I can confirm that I can reproduce the issue as described in the above comment in the latest stable version, apart from step 8 since the free version does not have database view. I made my own helloworld executable as such (using MinGW):
```c
#include <stdio.h>

int main()
{
	while(1)
	{
		printf("Hello world!\n");
		sleep(1);
	}
	return 0;
}
```

Regarding the rebasing, I did the initial rebase to 0x400000 because I was using Cheat Engine to assist in RE and it would report code addresses relative to the executable instead of absolute addresses. Rebasing it made it easier to jump to code in Binja.

**Comment by xusheng6** [comment]
There is a known issue that on the latest stable 4.1.5902 (f2165c5d), if you save the database while debugging, the database can get into an improper state and it may seem to have lose certain user annotations (e.g., function name, type, etc). The issue is caused by a bug in our handling of the memory map. The issue has since been fixed and is not affecting the latest development builds. For those who are using the latest stable version, you can either:

1) Switch to the latest development builds, and then you can save the database during debugging. You can do so following the user guide: https://docs.binary.ninja/guide/index.html#updates
2) If you have to stay with the latest stable, then please avoid saving your database during debugging. You will be fine if you save the database after the debugging has ended. 
3) If you have a database that is already corrupted, we can try to help you recover it. If you have an active support, please contact us via slack (https://slack.binary.ninja/) or email (binaryninja@vector35.com)

**Comment by xusheng6** [comment]
If you have a malfunctioning database caused by the above issue and you are also running a non-free version, you may try to recover it by yourself as well. Please remember this involves using a debug tool that we use during internal development so it may not be as reliable/stable as other parts of Binary Ninja.

Please read all of the instructions before you start!

1. Make a backup of your current database (REQUIRED STEP!)
2. Enable the setting `corePlugins.databaseViewer`
3. Restart Binary Ninja, and re-open the database
4. Navigate to the "Database" view and you should see something similar to this:

![Screenshot 2024-09-09 at 1 48 31 PM](https://github.com/user-attachments/assets/01d95028-9c0e-4a5f-8573-882934902364)

5. The database should now be at the last snapshot with the largest index. Right click on the previous snapshot, and click "Set Active Snapshot"
6. This will revert the database to the previous snapshot and may fix the issue. If it does not, try another earlier snapshot and see if it works
7. If you find a snapshot that works for you, save a clean copy of the database by "File"->"Save As"->"Save an analysis database". You should avoid working further from the original database, even if it appears to have been fixed
8. If it still does not work, please contact us for support via slack (https://slack.binary.ninja/) or email ([binaryninja@vector35.com](mailto:binaryninja@vector35.com))
