### ISSUE TITLE
Update documentation on how to set the working directory when using LLDB adapter for remote debugging

### ISSUE THREAD

**Issue by 5alv1** [Vector35/debugger#618]
Hello, I have just bought a personal license, before this I've never used binja directly to debug. I have a M1 macbook air, and thanks to QEMU I have a x64 Linux machine. I tried to connect to the lldb server, and when I try to to plugi>debugger>run error 8 pops out.

What's error 8? Is there something I'm doing wrong?
![image](https://github.com/user-attachments/assets/e516be14-d6f3-4f1b-b805-e10f827b94e3)
The path shown in the picture exists in my virtual machine

**Comment by 5alv1** [comment]
I used [https://docs.binary.ninja/guide/debugger/remote-debugging.html#lldb-server-recommended](this version of lldb) and now it says the directory doesn't exist. 
![image](https://github.com/user-attachments/assets/5141dc46-2afe-49e3-b3f7-973fd4aee773)
Is this supposed to exist on my host (my mac)?

**Comment by psifertex** [comment]
Just a heads up that the primary debugger developer is traveling so it might be a bit longer than normal before he can reply to this. 

One question -- are you running the latest stable or latest dev?

**Comment by 5alv1** [comment]
Might be a stupid question, how do I check for that? I got my license with a student discount and I only downloaded from the links I was sent, I might assume it's latest stable?

Edit: found this
![image](https://github.com/user-attachments/assets/dc308d2d-124a-4004-adb3-2213c2983321)
![image](https://github.com/user-attachments/assets/89cce134-53ab-4296-b09a-7b1bf88e9ced)

**Comment by xusheng6** [comment]
Could you please tell me how you connect to the Qemu machine from binary ninja?

**Comment by 5alv1** [comment]
1. I start the machine
2. I go to the directory where the ELF file I wanna debug is
3. I run ```lldb-server p --server --listen 0.0.0.0:9090```
4. I open Binary Ninja
5. Debug > Connect to Debug Server
6. I enter "remote-linux", the machine's ip address and the port 9090 (or whatever I used before)

![image](https://github.com/user-attachments/assets/e5b6c67b-b10f-4e14-81dc-4b8350ce9590)

![image](https://github.com/user-attachments/assets/6deb9ea5-8bb2-4640-b96e-0a7bb6adb751)

![image](https://github.com/user-attachments/assets/3611e6f5-2362-4e11-9502-813413f3b3c3)

Note that in these screenshots it's not the same executable, but I did have the same file both on my host and in my virtual machine. 
When I start the executable directly in the machine I can successfully attach the debugger to the process, but I want to be able to debug since the very beginning of the program.

**Comment by xusheng6** [comment]
> I used [https://docs.binary.ninja/guide/debugger/remote-debugging.html#lldb-server-recommended](this version of lldb) and now it says the directory doesn't exist. ![image](https://private-user-images.githubusercontent.com/46717588/371770601-5141dc46-2afe-49e3-b3f7-973fd4aee773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTQ2NTUsIm5iZiI6MTcyNzg1NDM1NSwicGF0aCI6Ii80NjcxNzU4OC8zNzE3NzA2MDEtNTE0MWRjNDYtMmFmZS00OWUzLWIzZjctOTczZmQ0YWVlNzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA3MzIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZjM5MzcwZjczNTBiMDhkZTVlODIyNWVlYTQyOGJkZWRiMDMyM2FlNGM1NTA0ZDNmMDY5YWE3MzZkYzZlNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e8n89JPIluyrRqBeMGxNZakLRWDS1lQtesICLYzdyVE) Is this supposed to exist on my host (my mac)?

When you launch the target, you will need to set the "Working Directory" in the "Debug Adapter Settings" dialog to the actual directory on the remote system (leave the executalbe path unchanged since it must be the local path). This is a bit confusing so I should really document it. Please let me know if it works for you!

**Comment by xusheng6** [comment]
Oh wait, it is already in the docs: https://docs.binary.ninja/guide/debugger/remote-debugging.html#connecting-to-a-debug-server-dbgeng-adapter

![Screenshot 2024-10-02 at 3 44 22 PM](https://github.com/user-attachments/assets/bab6677f-90de-48f6-99e3-bb64b6d89a22)

**Comment by xusheng6** [comment]
![Screenshot 2024-10-02 at 3 42 33 PM](https://github.com/user-attachments/assets/e73bd6c7-568b-4dd2-bb53-aecf2dc6f8bf)

**Comment by 5alv1** [comment]
> Oh wait, it is already in the docs: https://docs.binary.ninja/guide/debugger/remote-debugging.html#connecting-to-a-debug-server-dbgeng-adapter
> 
> ![Screenshot 2024-10-02 at 3 44 22 PM](https://github.com/user-attachments/assets/bab6677f-90de-48f6-99e3-bb64b6d89a22)
> 

Huh, I must have missed that, I'll try as soon as I have access to my drive, and I'll let you know. In the meantime, thank you for your help!

**Comment by xusheng6** [comment]
> > Oh wait, it is already in the docs: https://docs.binary.ninja/guide/debugger/remote-debugging.html#connecting-to-a-debug-server-dbgeng-adapter
> > ![Screenshot 2024-10-02 at 3 44 22 PM](https://private-user-images.githubusercontent.com/94503187/372774561-bab6677f-90de-48f6-99e3-bb64b6d89a22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTU5ODUsIm5iZiI6MTcyNzg1NTY4NSwicGF0aCI6Ii85NDUwMzE4Ny8zNzI3NzQ1NjEtYmFiNjY3N2YtOTBkZS00OGY2LTk5ZTMtYmI2NGI2ZDg5YTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA3NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjAxMDM5MDExZWFjOGFiNzExODNhMTU3NjUzMWYyMDVhMGNmNTAwYzc1Njc2OWYzNjdkOGEzOGI1NTQzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vdI7dPSZLihlI0c6VBPM5Bvz_0w5fz9_XZuk8dRVMOw)
> 
> Huh, I must have missed that, I'll try as soon as I have access to my drive, and I'll let you know. In the meantime, thank you for your help!

It is not your fault -- you are probably a victim of https://github.com/Vector35/debugger/issues/619

**Comment by 5alv1** [comment]
This doesn't work either, not it shows this error

![image](https://github.com/user-attachments/assets/233f7d0f-48b8-4486-bc18-c3582b5c3db2)

**Comment by xusheng6** [comment]
> This doesn't work either, not it shows this error
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/233f7d0f-48b8-4486-bc18-c3582b5c3db2)
> 
> 

Can you show me a screenshot of the debug adapter settings dialog before you launch it?

**Comment by 5alv1** [comment]
![image](https://github.com/user-attachments/assets/13f4eb2a-d2ba-4204-8a49-0bfa3fb7118e)

"shellcrunch" is both the name of the executable and the name of the directory, I also tried in the home directory, and it gave me the same error. I also tried to put the absolute path in "Executable path"

**Comment by xusheng6** [comment]
> ![image](https://private-user-images.githubusercontent.com/46717588/373022795-13f4eb2a-d2ba-4204-8a49-0bfa3fb7118e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MTkzOTcsIm5iZiI6MTcyNzkxOTA5NywicGF0aCI6Ii80NjcxNzU4OC8zNzMwMjI3OTUtMTNmNGViMmEtZDJiYS00MjA0LThhNDktMGJmYTNmYjcxMThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDAxMzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYTEwYjlmOTM4MDc1ZmQ1M2VhZmYxNzNlOTBkYjBhYzE0NjRiYTEwYmYxYjRhMjYwZjkzM2MwZjFhYzY1YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8FuSsepjQmYMMoP_KaMhx-6d7RAmjiXSOLBROOKDscY)
> 
> "shellcrunch" is both the name of the executable and the name of the directory, I also tried in the home directory, and it gave me the same error. I also tried to put the absolute path in "Executable path"

The Executable path needs to be the absolute path on the local system. You can set it to the same as the Input File

**Comment by 5alv1** [comment]
Ok, now it works (I can't read)

Thank you for your time

**Comment by xusheng6** [comment]
> Ok, now it works (I can't read)
> 
> Thank you for your time

I am glad that it now works for you. I am closing this for now. Please free to ping me if there are any other issues
