### ISSUE TITLE
Old versions of the debugger docs are still available online and are preferred by search engines

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#619]
During a customer support session, I realized the old version of the debugger docs, i.e., https://docs.binary.ninja/guide/debugger.html, is not only still online, but also preferred by the search engine. It is hard to find the latest docs at https://docs.binary.ninja/guide/debugger/index.html

**Comment by psifertex** [comment]
Done (specifically I replaced it with a redirect)

**Comment by xusheng6** [comment]
We need these redirects:

https://docs.binary.ninja/guide/debugger.html --> https://docs.binary.ninja/guide/debugger/index.html
https://docs.binary.ninja/guide/remote-debugging.html --> https://docs.binary.ninja/guide/debugger/remote-debugging.html
https://docs.binary.ninja/guide/dbgeng-ttd.html --> https://docs.binary.ninja/guide/debugger/dbgeng-ttd.html

**Comment by psifertex** [comment]
The first URL redirect was already done -- it's the same as the one above. Was it supposed to be a different URL? Just did the other two.

**Comment by xusheng6** [comment]
> The first URL redirect was already done -- it's the same as the one above. Was it supposed to be a different URL? Just did the other two. 

Yeah the first one is already done. I just added it for record keeping
