### ISSUE TITLE
LLDB Failed to launch target with "error: failed to launch or debug process" on MacOS ARM (M3)

### ISSUE THREAD

**Issue by MayankPandey01** [Vector35/debugger#623]
**Version and Platform (required):**
- Binary Ninja Version:4.1.5902 (2024-08-16)
- OS: MacOS
- OS Version: 14
- CPU Architecture: M3

**Bug Description:**
I get `LLDB Failed to launch target with "error: failed to launch or debug process"` whenever I try to run a binary 

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to Debugger
2. Click on run
3. You can see this error

<img width="447" alt="image" src="https://github.com/user-attachments/assets/449578ed-f192-46f4-951c-07ae0564ca61">

<img width="366" alt="image" src="https://github.com/user-attachments/assets/f7fb9945-3522-4c8c-993c-09622b78969f">

lldb actually launches from the CLI with the provided binary but fails with binary ninja

**Binary:**
This is a Binary from PICO CTF

https://drive.google.com/file/d/1tlhPzcfCpd8t2lmfS52KP3QfS6a72XWU/view?usp=sharing

**Comment by xusheng6** [comment]
This is a Linux binary and it would not run on macOS:

```
bin: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=ed9d01aa375e575eb2cd16506aa83d6951841f87, for GNU/Linux 3.2.0, not stripped
```

You will need to set up remote debugging for it: https://docs.binary.ninja/guide/debugger/remote-debugging.html

The LLDB command line can launch with it, but I guess it could not debug it as well
