### ISSUE TITLE
Be able to debug Libraries or DLL 

### ISSUE THREAD

**Issue by Xoffio** [Vector35/debugger#63]
If I want to debug a library or a plugin on macOS I can use Hopper which gives you the chance to set the path of the main program that will load the plugin into memory. Then they manage to map the addresses once is loaded and I can debug the plugin. I don't know how they made it happen but it works very well.

If Binja is able to do this with its debugger it would be awesome. I have been doing some research about it and I think we can make it work. Keep in mind I am doing the testing on Win but the goal is to make it work on all architectures.

First we have to update the UI to let the user set the path of the executable (I had to go to the code a do it manually to test it out)

I had taken a couple of days to learn how to use Windbg and I find out that we can do this:

Break once the module loads into memory
> sxe ld:moduleName.dll

Get the address of the module
> x moduleName*!
start             end                 module name
`00000000901f0000` `000000009329d000`   moduleName C (export symbols)       C:\Program Files\Company\CompanyFX2020\Support Files\Plug-ins\moduleName.aex

Now I have:
- The base address of the module loaded into memory: `0x901f0000`
- The base address in Binja: `0x180000000`
- The address of the breakpoint in Binja: `0x1819165cf`

> hex(0x1819165cf-0x180000000+0x901f0000)

With this a can map/translate the breakpoints on Binja to the addresses of the loaded module into memory.

**Comment by xusheng6** [comment]
Fixed in https://github.com/Vector35/binaryninja/commit/6ba87ad282dff5831daa14b29f18cef40acce36a
