### ISSUE TITLE
Need new icon for the deubgger info widget

### ISSUE THREAD

**Issue by xusheng6** [Vector35/debugger#644]
Currently the debugger info widget uses the same icon as the debugger widget. We need a new one for it:

![Screenshot 2024-10-30 at 10 41 26 AM](https://github.com/user-attachments/assets/27dd96c6-4073-4c31-80ab-9ece0667dfaf)

**Comment by fuzyll** [comment]
It was decided we should go with an icon I designed of a CCTV camera, which I've just shipped in builds >= 4.2.6374-dev. But, I am not sure this will correctly convey to users that this is a debugger feature or even that this is a thing to "watch". So, I've also committed an alternative icon with a bug on a monitor that I think is less cool, but maybe conveys the idea better to the main repo. We can switch to this, or any other idea we have, in the future if necessary.
