### ISSUE TITLE
Make "F4" key binding default to "Run To Here"

### ISSUE THREAD

**Issue by blue-devil** [Vector35/debugger#645]
Hello folks;

One of the best things in a debugger is `Run To Here` debug command. That makes debugging faster.
But on Binary Ninja we don't have a key binding of it. Generally `F4` is used for that:

| App Name | Operation Name | Key Binding|
| --- | ---- | --- |
| IDA Pro | `Run to cursor` | `F4` |
| x64dbg | `Run Until Selection` | `F4` |
| Binary Ninja | `Run To Here` | not set |

Quick and personal workaround:
`Ctrl + P (Command Palette) > Key Bindings` and then set `F4` for key binding.

My wish is; can you consider making `F4` keybinding default for `Run To Here` debug command?

Thank you.

**Comment by xusheng6** [comment]
Sounds like a good idea. I did not even know other tools do it

**Comment by xusheng6** [comment]
Added in https://github.com/Vector35/debugger/commit/7a5b384cca01e6064283272a5efe70922d4a7c63
