### ISSUE TITLE
Debugger Build Documentation Incorrect

### ISSUE THREAD

**Issue by 1ikeadragon** [Vector35/debugger#661]
### Summary 

The build instructions for the Binja Debugger are incorrect because one of the required and supplied components: [lldb-artifacts](https://github.com/Vector35/lldb-artifacts/releases) doesn't contain the required files in the correct format. When followed the steps to the T, it produces error. 

### Steps to Replicate:

1. Follow the [debugger build docs](https://github.com/Vector35/debugger/blob/dev/build.md).
2. You will get the error message: 
![image](https://github.com/user-attachments/assets/dc6412cc-768d-464c-a5d1-8c246a22a93c)

### Suggestion:

Provide the lldb-artifact zip with all the files required in the right format.

Current workaround:
```sh
cd ~/libclang/16.0.0/lib
ln -s liblldb.16.0.0.dylib liblldb.dylib
~/libclang/16.0.0/bin
cp /path/to/binja/darwin-debug .

```

**Comment by xusheng6** [comment]
Thx for the bug report! Two fixes are needed:

1. Rebuild LLDB and update the artifact archive to include the `darwin-debug` executable
2. Update the CMakeLists.txt (https://github.com/Vector35/debugger/blob/910b5f1660bd35af228943ba5a7a45144702658a/core/CMakeLists.txt#L107) to ensure `liblldb.16.0.0.dylib` can be found
