### ISSUE TITLE
Show addresses with RTTI, classes and function names information

### ISSUE THREAD

**Issue by marcusx2** [Vector35/debugger#67]
Pardon me if it's already implemented. I can't test this plugin on demo version. I mean something like this:

![Untitled](https://user-images.githubusercontent.com/5656275/85262972-e1f61c80-b444-11ea-8004-6932e9faee2c.png)

I find that it helps a **lot** with reversing.

**Comment by xusheng6** [comment]
I think this issue is not really a debugger issue -- should it be done by binary ninja?

**Comment by xusheng6** [comment]
I am closing this in favor of https://github.com/Vector35/binaryninja-api/issues/3930. The RTTI info will be process by binary ninja directly, and the debugger does not need to do anything for it
