### ISSUE TITLE
Live memory repeats register name when labelling an address

### ISSUE THREAD

**Issue by lwerdna** [Vector35/debugger#76]
If an address is also the value of a register, the address gets labelled with that register (GOOD!) but repeated with a colon (BAD!). For instance if $rsp is 0x7ffeedad7c98, it gets labelled `$rsp:$rsp`. That colon has meant bit concatenation or segment:offset in my experience.

Here's a screenshot exhibiting the problem with `$rsp:$rsp`, `$rsi:$rsi`, `$rdx:$rdx`:

![Screen Shot 2020-04-28 at 1 31 48 PM](https://user-images.githubusercontent.com/474191/80518787-f510d280-8954-11ea-9df3-717781fa4bb1.png)

**Comment by xusheng6** [comment]
Tracked in https://github.com/Vector35/debugger/issues/171
