### ISSUE TITLE
better documentation for backend installation

### ISSUE THREAD

**Issue by psifertex** [Vector35/debugger#81]
We should have exception handling to better tell the user what they need to do to get backends working. IE, on ubuntu: `sudo apt install gdbserver`
MacOS: `xcode-select --install` I think is all that's required?
Windows: ?

Additionally -- that information should be in the installation instructions available both in the readme and in the debugger installation instructions json field so it's shown in the plugin information.

**Comment by xusheng6** [comment]
We now bundle the back-ends needed so this is no longer needed
