### ISSUE TITLE
Create/Attach BinaryViews for loaded modules

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/debugger#82]
When debugging a binary that calls library functions, we can load a new BinaryView from the module path and get analysis for those functions as well. This should definitely be optional as some processes (especially on macOS) load a lot of large libraries.

Inter-BV analysis is an entirely different (and much harder) problem for BN core, and if it ever is implemented it would be great to include. Not the focus of this issue though.

**Comment by xusheng6** [comment]
related to: https://github.com/Vector35/debugger/issues/63.

**Comment by xusheng6** [comment]
Now tracked by https://github.com/Vector35/debugger/issues/207
