### ISSUE TITLE
x86_64 sub-registers

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/debugger#91]
Currently eax, ebx, ecx, edx, and edi are showing in the registers list. We should either show all 32-bit registers (i.e. include esi, esp, ebp, r8d, r9d, etc) or show none of them.
The same goes for the 16-bit and 8-bit registers, including the high 8-bit registers (ah, bh, ...)

Environment: macOS + lldb

**Comment by xusheng6** [comment]
Related to https://github.com/Vector35/debugger/issues/221 and https://github.com/Vector35/debugger/issues/230

**Comment by xusheng6** [comment]
Currently we are showing all registers including sub-registers. The full list is very long, but thanks to the "hide unused registers", the list are often times elegantly short. This issue seems no longer relevant, given that we have #221 and #230
